### ISSUE TITLE
Error using syte theme

### ISSUE THREAD

**Issue by tschertel** [getpelican/pelican-themes#109]
When I configure pelican to use syte theme ad call "make html", I get this error message:
CRITICAL: Encountered unknown tag 'assets'.

All I get in output folder is a "theme" folder with a few files in it.

**Comment by bretonio** [comment]
Decades later a similar issue. I typed `sudo pip install webassets` and then `sudo pip install cssmin` and yet the error persists. 

Attempting to use `THEME = 'eevee'. 

No such error with `THEME = 'notmyidea'`.

**Comment by cesarmarroquin** [comment]
I get the same exact error as @bretonio  trying to use the 'eevee' theme.  Both of those packages are installed for me as well.

**Comment by mirzal** [comment]
@bretonio @cesarmarroquin did you guys add `assets` plugin in `pelicanconf.py`? `eevee` theme depends on it (i.e. installing `webassets` package is not enough).

```
PLUGINS = [
    'assets'
]
```

**Comment by JordanRex** [comment]
i faced this issue again. theme = 'eevee' is not working out for the exact same circumstances above
