### ISSUE TITLE
gum - does not display bullets

### ISSUE THREAD

**Issue by tshepang** [getpelican/pelican-themes#152]
if you have rST like this:

    * item 1
    * item 2
      * item 2.1
      * item 2.2

the output will come out like:

    item 1
    item 2
       item 2.1
       item 2.2

**Comment by caesar0301** [comment]
The same problem. Is it solved now?

**Comment by dzarda** [comment]
Is this theme dead?
The problem is most definitely missing .pngs
@almarklein Got it right - `list-style: none` is the problem. I have no idea if it is a feature, but definitely not working out for me.
If I were to make a pull request fixing this somehow, would it get attention? :)

**Comment by justinmayer** [comment]
@dzarda: If you would be so kind as to submit a pull request to fix this issue, I'd be happy to ensure it gets proper attention.  (^_^)

**Comment by jasonrhaas** [comment]
hey @justinmayer I just created pull request #329 to resolve this :+1:

**Comment by justinmayer** [comment]
Many thanks to @jasonrhaas for addressing this issue.  (^_^)
