### ISSUE TITLE
a simple question to addition of images,

### ISSUE THREAD

**Issue by d-yu** [getpelican/pelican-themes#307]
For the configuration of this Theme, we see:

You can provide a logo for your site using SITELOGO. 
For example: SITELOGO = 'images/my_site_logo.png'. 

could anyone kindly tell me what is the path for    'images/my_site_logo.png'.  
is this the relatiive path to the configuration file or ? 
where is the " images" folder? 

thank you very much

**Comment by justinmayer** [comment]
I imagine the path is relative to the content folder.

**Comment by d-yu** [comment]
@justinmayer  you are right! 
thanks a lot
