### ISSUE TITLE
Ask theme authors to specify the license of their theme

### ISSUE THREAD

**Issue by cdman** [getpelican/pelican-themes#331]
A lot of themes don't make it clear what license they are available under. This means technically that they are "all rights reserved" and as such can't be used by others for their websites. Could we please ask the theme authors to add a LICENSE file to their theme as a prerequisite of being included in this directory?

**Comment by aloisdg** [comment]
see #277

**Comment by cdman** [comment]
Thank you, I'm closing this issue then.

**Comment by aloisdg** [comment]
You are welcome.
