### ISSUE TITLE
Support for series in pelican-bootstrap3 theme

### ISSUE THREAD

**Issue by Sirtea** [getpelican/pelican-themes#343]
Hi,

As seen on DandyDev/pelican-bootstrap3, should be desirable to add series support to the copy on this repository. Please consider this option.

Regards

**Comment by lgiordani** [comment]
@Sirtea you should ask @DandyDev to merge the code here. Actual development of pelican-bootstrap3 happens on his repository.

**Comment by Sirtea** [comment]
I thought it was the other way round...

Thanks; I'll do that
