### ISSUE TITLE
Bullets do not appear in the gum theme

### ISSUE THREAD

**Issue by adamatan** [getpelican/pelican-themes#356]
I've added the following `reStructuredText` to a post using the `gum` theme:

```
**Common use cases might be:**

- Consuming message from a queue
- Making periodic HTTP calls to a site for monitoing purposes
```

The resulting HTML is indeed an unordered list:
![screen shot 2016-01-03 at 14 21 46](https://cloud.githubusercontent.com/assets/1014189/12078723/b084d356-b225-11e5-9f23-62817fc21c1e.png)

The rendered page, however, does not feature any bullets:
![screen shot 2016-01-03 at 14 17 45](https://cloud.githubusercontent.com/assets/1014189/12078720/9d0d800c-b225-11e5-986e-1e626db6eae3.png)

This is technically OK because HTML unordered lists do not have to feature a bullet, but I think that the expected (and correct) manifestation of a `<ul>` should be formed with bullets.

**Is this a bug or a feature, and how can we fix it?**

**Comment by born2discover** [comment]
Hello there,

That just might be a feature. But you could change that by adding custom CSS or modifying the theme CSS by adding (as per [this](http://www.w3schools.com/cssref/pr_list-style-type.asp) specification) something like this:
```css
ul.simple {
    list-style: disc
```

**Comment by adamatan** [comment]
Thanks.
Not sure why it's not the default, though. If a writer places an unordered list in the MD or ReST document, the writer expects to see it in HTML.

**Comment by rask004** [comment]
Keeping issue age in mind:

gum theme now has bullet points for unordered lists as default. Bullet points only disappear if the `clear` class is applied to the `ul`.

Suggest closing this issue.
