### ISSUE TITLE
Add instructions to readme for updating repository

### ISSUE THREAD

**Issue by mlissner** [getpelican/pelican-themes#363]
I used pelican months ago, so I have pelican-themes on my system, but I know it has submodules, which are an area of git that I never play with. You have instructions for the initial clone, but it'd be great to have some for updating as well. 

This looks promising, but I really have no idea: https://stackoverflow.com/questions/1030169/easy-way-pull-latest-of-all-submodules

**Comment by born2discover** [comment]
Hello there,

As per [this](http://stackoverflow.com/a/4438292/666454) StackOverflow answer, all you have to do is:
```shell
git submodule update --init --recursive
```

**Comment by rask004** [comment]
Recommend closing this issue, is not as theme issue.

**Comment by justinmayer** [comment]
@rask004: Agreed. Many thanks for going through some existing issues/PR and helping to review them. That kind of assistance is SUPER helpful. Bravo! 😄
