### ISSUE TITLE
Bootstrap2 red outlined boxes in code blocks

### ISSUE THREAD

**Issue by sevagh** [getpelican/pelican-themes#381]
Hello,

I noticed that some text in my code blocks have red outlined boxes. I can't seem to find a pattern of what's causing it.

SCREENSHOT:

![bootstrap2-red-boxes](https://cloud.githubusercontent.com/assets/8574092/14073090/1992ec10-f494-11e5-8062-103f2dd9e6ac.png)

This is the markdown file:

https://raw.githubusercontent.com/sevagh/blog/master/content/11-i3-no-dm-p2.md

This is the article pushed on gh pages (with the "make github" directive):

http://sevagh.github.io/blog/i3-with-no-dm-part-2.html

**Comment by sevagh** [comment]
In the generated HTML/CSS the red highlighted boxes are "<span class="err">

**Comment by sevagh** [comment]
To workaround I can just use \<pre><code></code></pre> in the markdown files but it seems entirely arbitrary which span class is used for different characters in a singe markdown indented block of code.

**Comment by justinmayer** [comment]
Always a good idea to check existing issues: https://github.com/getpelican/pelican/issues/1170

**Comment by sevagh** [comment]
Thanks @justinmayer.
