### ISSUE TITLE
Generated a view of all themes.

### ISSUE THREAD

**Issue by Granitosaurus** [getpelican/pelican-themes#431]
Hello,
I wrote a view generator for projects like these called [`gh-theme-display`](https://github.com/Granitas/gh-theme-display) and I ran it on pelican-themes with surprisingly good results: https://github.com/Granitas/gh-theme-display/blob/master/examples/getpelican-pelican-themes.html
So maybe this would warrant adding it somewhere for easier browsing?

**Comment by iranzo** [comment]
For easier browsing of resulting file:

https://htmlpreview.github.io/?https://github.com/Granitosaurus/gh-theme-display/blob/master/examples/getpelican-pelican-themes.html

I think it should be good to run it periodically with latest versions of plugins at #645 and #630 to have a clear idea of what works and what not

**Comment by avaris** [comment]
Fixed in #748
