### ISSUE TITLE
No submodule mapping found in .gitmodules for path 'ops'

### ISSUE THREAD

**Issue by shouptech** [getpelican/pelican-themes#463]
Attempting to do a recursive clone of this repository results in an error:

    $ git clone --recursive https://github.com/getpelican/pelican-themes
    Cloning into 'pelican-themes'...
    [...]
    No submodule mapping found in .gitmodules for path 'ops'

**Comment by antiphasis** [comment]
Can anyone responsible please fix the .gitmodules file? 
Some themes are missing, e.g. monospace, and at least one entry is void, making it unable to checkout the themes. 
As a workaround i've forked the themes repo, will kick the fork as soon as this one is fixed.
