### ISSUE TITLE
pelican-bootstrap3: CSS requests are blocking (not loading async)

### ISSUE THREAD

**Issue by gravyboat** [getpelican/pelican-themes#472]
So I've been working on some more site optimizations recently and noticed that there are some blocking elements when the page loads, the following section is the most problematic and will ding you in terms of performance:

https://github.com/getpelican/pelican-themes/blob/master/pelican-bootstrap3/templates/base.html#L57-L77

I'm already leveraging http2 on my personal web server to get around this for the most part but it might be nice for backwards compatibility (not sure if we can just use the async tag content from HTML5 or not) and for any sort of third party that ranks your site you'll still lose points due to how they test.

**Comment by colinbrislawn** [comment]
Good idea. Google dings me for this css as well.

Would the fix be as easy as just moving them [down with the other scripts](https://github.com/getpelican/pelican-themes/blob/master/pelican-bootstrap3/templates/base.html#L217)?

Was there a reason they were put at the start in this design?

**Comment by gravyboat** [comment]
@colinbrislawn I actually did that for a fork for a custom theme I needed: https://github.com/gravyboat/pelican-themes/blob/master/pelican-bootstrap3-grid/templates/base.html#L157 and that fixed a lot of it for me. I had to leave a few of them in specific areas otherwise the initial page rendering looked very awkward for some browsers.

**Comment by colinbrislawn** [comment]
Are you considering submitting at PR? I think many people could make use of this, including me!

**Comment by gravyboat** [comment]
@colinbrislawn I wasn't planning on it because it's for a different theme. I wasn't sure if there was a reason it was designed like that in the first place. Looks like I did make the same change in the main theme though: https://github.com/gravyboat/pelican-themes/blob/master/pelican-bootstrap3/templates/base.html#L157 If you want to grab it and open a PR feel free to do so, my commit notes are pretty messy.
