### ISSUE TITLE
Some themes using "loop" throw a critical error when creating the blog

### ISSUE THREAD

**Issue by MrMovl** [getpelican/pelican-themes#481]
Hi there, this one is kind of strange. A lot of themes are broken for me, in fact, every theme which uses "loop" somewhere in any template. Even in 4 year old themes. I am not sure if I have a strange setup, but I don't think so.

Basically, if I add the following line to my pelicanconf.py
`THEME = "/home/me/workspace/pelican-themes/nmnlist"`
and then run the build with `make html` I get the following error:
`CRITICAL: UndefinedError: 'loop' is undefined`
`Makefile:65: recipe for target 'html' failed`
`make: *** [html] Error 1`

I also get that error when building manually using
`pelican content -o output -s pelicanconf.py`

Maybe this has a simple solution, but I was not able to find anything.

The project I used here is not much more then what `pelican quickstart` generates, except two about me articles (in two languages).

Let me know if any additional info is necessary.

**Comment by justinmayer** [comment]
Hi Tomke. As mentioned in the [Getting Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the docs, please test with the default "notmyidea" theme. Assuming you don't see the error with that theme, try comparing that theme's source to ones where you get the error and see if you can determine the difference that's causing the problem. Thanks for helping to track this down!

**Comment by MrMovl** [comment]
Sure, sorry, should have thought of including that info.

I can use the _notmyidea_ theme from the pelican repo as well as several others from this repo (working examples are _bootstrap2-dark_, _Flex_ and _Medius_).

I first thought all themes containing the loop keyword did not work (like [line 8 here](https://github.com/getpelican/pelican-themes/blob/master/nmnlist/templates/index.html)). But I just saw that the _notmyidea_ theme from the pelican repo also uses `loop`. But maybe all themes from this repo using _loop_ are broken. I haven't had the time to test them all, but testing a few seemed to confirm that suspicion.

My python is a little rusty, so I wonder where loop comes from in the template mentioned above. But I went ahead and removed all loop instances from the _nmnlist_ theme ([index.html](https://github.com/getpelican/pelican-themes/blob/dc96229e91ff554ba712c1316103c5d9e4422629/nmnlist/templates/index.html) and [base.html](https://github.com/getpelican/pelican-themes/blob/dc96229e91ff554ba712c1316103c5d9e4422629/nmnlist/templates/base.html)), the resulting files are in this [little gist](https://gist.github.com/MrMovl/f7be92a293146f94a378901e3ead8af9).
With these changes the theme compiles.

I first suspected some problem with wrong python versions, but I tested this on Manjaro Linux, Linux Mint and an Ubuntu Server.

Letme know what else you need.

**Comment by piorekf** [comment]
@MrMovl The error is not because of line 8 in that file but rather line 28. It tries to use loop variable outside of for loop.

**Comment by justinmayer** [comment]
Thanks for the helpful tip, Piotrek. Much appreciated!

**Comment by kmannarbor** [comment]
Hi, I'm having a similar problem. When I try to use pelican-bootstrap3, it returns the following error:

CRITICAL: UndefinedError: '_' is undefined
make: *** [Makefile:44: html] Error 1

I have tested the default (notmyidea) theme and it works great. Also, like MrMovl, bootstrap2-dark and medius work just fine as well. I'm not sure if the code you posted would work in my situation and I'm unsure where to copy that code. Any help would be greatly appreciated!

**Comment by justinmayer** [comment]
@kmannarbor: `make` is simply an automation wrapper around the core `pelican` command. As such, I recommend using `pelican` commands whenever debugging.

**Comment by avaris** [comment]
@kmannarbor probably related to #460
