### ISSUE TITLE
Pelican-bootstrap3 : Undefined error '_'

### ISSUE THREAD

**Issue by aaa34169** [getpelican/pelican-themes#482]
Hi 
I am novice with bootstrap3 theme. I clone the bootstrap3 folder and copy-paste in my pelican project folder in a subdirectory theme/bootstrap3 the both bootstrap3 theme folders : static and template

my pelicanconf mentions: 
```
THEME = "./Theme/boostrap3"
BOOTSTRAP_THEME = 'flatly'     
```

when i run make html
i get this error : 
CRITICAL : undefinedError :'_' is undefined. 
![2017-01-24 12_12_13-new issue getpelican_pelican-themes](https://cloud.githubusercontent.com/assets/3098117/22246926/29be3020-e22f-11e6-8b4c-cf13b2fca162.png)

how an i fix that

cheers 

Fabien

**Comment by mr-ubik** [comment]
I am having this issue too.

**Comment by crazy-canux** [comment]
Did you fixed this?

**Comment by mr-ubik** [comment]
I did, I am not sure why but apparently you need to setup the jinja plugin. 
```
PLUGIN_PATHS = ['path/to/plugins', ]
PLUGINS = ['i18n_subsites', ]
JINJA_ENVIRONMENT = {
    'extensions': ['jinja2.ext.i18n'],
}
```
If this works please teel me and I will do a PR to change the README

**Comment by crazy-canux** [comment]
Yes，but I got the new error:
CRITICAL: UndefinedError: 'gettext' is undefined

**Comment by crazy-canux** [comment]
I am using pelican3.7.1

**Comment by mr-ubik** [comment]
@crazy-canux  you should open a new issue in regard to this error and possibly give more info on your config. I would suggest stripping your `pelicanconf.py` of all sensible data and posting it together with a `pip freeze > packages.txt` of your current in use packages.

**Comment by crazy-canux** [comment]
#460

**Comment by crazy-canux** [comment]
I changed to another theme codeing-now.
thanks！

**Comment by mixmastamyk** [comment]
https://github.com/pallets/jinja/issues/363

**Comment by stuaxo** [comment]
I tried out pelican and pelican-bootstrap3 from git and get the same error -

I had this snippet in my config

```python
PLUGINS = ['i18n_subsites', ]
JINJA_ENVIRONMENT = {
    'extensions': ['jinja2.ext.i18n'],
}

```

Before the gettext error I noticed:

```
ERROR: Cannot load plugin `i18n_subsites`
```

Here is the output of pip freeze
```
$ pip freeze
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
blinker==1.4
certifi==2017.7.27.1
decorator==4.1.2
docutils==0.14
enum34==1.1.6
feedgenerator==1.9
feedparser==5.2.1
ipdb==0.10.3
ipython==5.5.0
ipython-genutils==0.2.0
Jinja2==2.9.6
livereload==2.5.1
lxml==4.0.0
Markdown==2.6.9
MarkupSafe==1.0
pathlib2==2.3.0
pelican==3.7.1
pexpect==4.2.1
pickleshare==0.7.4
pkg-resources==0.0.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
python-dateutil==2.6.1
python-gettext==3.0
pytz==2017.2
scandir==1.6
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
tornado==4.5.2
traitlets==4.3.2
Unidecode==0.4.21
wcwidth==0.1.7

```

**Comment by jodumont** [comment]
I resolve this by 

1. git clone https://github.com/getpelican/pelican-plugins.git pelican-plugins

2. adding in pelicanconf.py

```
PLUGIN_PATHS = ['/path/to/git/pelican-plugins', ]
PLUGINS = ['i18n_subsites', ]
JINJA_ENVIRONMENT = {
    'extensions': ['jinja2.ext.i18n'],
}
```

obviously you need to change the '/path/to/git/ part ;)

**Comment by polkapolka** [comment]
I was having this issue as well. I tracked it down to a conflict between Jinja2 and Pelican.  Jinja expects some defined variables that aren't present in older versions of pelican.  I was able to solve the problem by upgrading both jinja2 and pelican.

```pip install --upgrade pelican```

My versions now are 
```pelican 3.7.1```
```jinja2 2.10```

**Comment by justinmayer** [comment]
Many thanks to everyone for contributing to this thread. Marking as resolved.

**Comment by sodonnell** [comment]
Problem still persists in 4.2.0 using pelican-bootstrap3 under python 3.6.8.

> I resolve this by
> 
> 1. git clone https://github.com/getpelican/pelican-plugins.git pelican-plugins
> 2. adding in pelicanconf.py
> 
> ```
> PLUGIN_PATHS = ['/path/to/git/pelican-plugins', ]
> PLUGINS = ['i18n_subsites', ]
> JINJA_ENVIRONMENT = {
>     'extensions': ['jinja2.ext.i18n'],
> }
> ```
> 
> obviously you need to change the '/path/to/git/ part ;)

The problem still persists using pelican 4.2.0 w/ pelican-bootstrap3 and python 3.6.8, but this comment (above) does resolve the issue.
