### ISSUE TITLE
mnmlist-based-on themes CRITICAL: UndefinedError: 'loop' is undefined

### ISSUE THREAD

**Issue by Bricabraque** [getpelican/pelican-themes#487]
When I try to generate a pelican site with themes based on mnmlist, the prompt tells me this:

`CRITICAL: UndefinedError: 'loop' is undefined`

I've tried with default mnmlist theme and new pelican installation, but it still does not work and I can't figure out why.

**Comment by jaduse** [comment]
Encountered the same problem. Write fix on that.

**Comment by jaduse** [comment]
https://github.com/getpelican/pelican-themes/pull/490

**Comment by Bricabraque** [comment]
Thanks a lot, problem solved !
