### ISSUE TITLE
Can't go back to index.html

### ISSUE THREAD

**Issue by JekoTronik** [getpelican/pelican-themes#502]
Hi ! I use the mnmlist theme and i am facing a no sense problem.
When I read an article (http://blog.url/article.html) the link with the blog name which is supposed to bring me back to index.html is keeping me on the active article.
The strange thing is that I don't know why because the template/article.html seems ok... Does someone has  experiencing such thing?
Here an extract of template/article.html
```
<header>
    <h1><a href="{{ SITEURL }}" id="site-title">{{ SITENAME }} {% if SITESUBTITLE %} <strong>{{ SITESUBTITLE }}</strong>{% endif %}</a> :
        <a href="{{ SITEURL }}/{{ article.url }}" id="page-title">{{ article.title }}</a></h1>
    {% if not HIDE_DATE %}<time datetime="{{ article.date.isoformat() }}">{{ article.locale_date }}</time>{% endif %}
</header>
```
So in reality, SITEURL seems equal to SITEURL/article.url. 
(If it helps, my fresh blog is at http://jeko.frama.io)

**Comment by joshmorel** [comment]
The theme should be using: 

`<a href="{{ SITEURL }}/" > ... </a> `

Note the forward slash.

However, even if with that issue, you should be able to get it to work with the following in your settings file:

`SITEURL = 'http://jeko.frama.io'`

I'm trying to generate my site with this theme but getting a `UndefinedError: 'loop' is undefined` ... not sure why.

**Comment by JekoTronik** [comment]
Hi @joshmorel !

Thank you for considering my issue ! Very kind !

I tried with the slash, with `pelican content` and open my public/index.html and it worked. Then i removed the slash, and it was still OK. I don't understand. ^^

I encourtered your error and I solved it following a comment [here](https://github.com/getpelican/pelican-themes/issues/481) .

**Comment by justinmayer** [comment]
Glad you were able to resolve your issue. :smile:
