### ISSUE TITLE
Submodule update error for theme "Casper2Pelican"

### ISSUE THREAD

**Issue by hartwork** [getpelican/pelican-themes#527]
```
# git submodule update --depth 1 
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
error: Server does not allow request for unadvertised object 2e17c16378e43705a47533038144bed38ca8af4c
Fetched in submodule path 'Casper2Pelican', but it did not contain 2e17c16378e43705a47533038144bed38ca8af4c. Direct fetching of that commit failed.
```

**Comment by jeffwidman** [comment]
This may be a somewhat recent Github change: 
https://news.ycombinator.com/item?id=14552172 and https://github.com/sorin-ionescu/prezto/issues/1431

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…

**Comment by justinmayer** [comment]
Thanks for filing this issue, Sebastian, and apologies for the delay in responding to it.

Since the relevant theme was archived, we addressed this a while ago via https://github.com/getpelican/pelican-themes/commit/cb986aa432759233dee963c1430ab502ac57dbec.
