### ISSUE TITLE
http://www.pelicanthemes.com/ is dead

### ISSUE THREAD

**Issue by jkugler** [getpelican/pelican-themes#537]
Going to http://www.pelicanthemes.com/ results in
```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
```

**Comment by m-allanson** [comment]
This is [fixed now](https://github.com/m-allanson/pelican-themes/commit/d44dc37cbe18b78f58b9af950eef3da136b82684). Let me know if anyone from the getpelican team would like to be added as a collaborator to the Github repo or Heroku app.

**Comment by kidig** [comment]
@m-allanson It's dead again!

**Comment by m-allanson** [comment]
It's back. I'm happy to add anyone as a collaborator as I don't have much time to maintain the site any more.

**Comment by justinmayer** [comment]
Hi Mike. Thanks for all the time and energy you've put into pelicanthemes.com. Would you be so kind as to add me as a collaborator to the Github repo / Heroku app?

**Comment by m-allanson** [comment]
No problem, I wrote it several years ago as a learning exercise and it's mostly kept itself running since then.  I don't write much Python these days and never got around to adding any of the improvements I'd thought about.

GitHub invite sent and I've contacted you about Heroku.
