### ISSUE TITLE
License for aboutwilson

### ISSUE THREAD

**Issue by adrn** [getpelican/pelican-themes#544]
Related to #277, I don't see a LICENSE file in the `aboutwilson` theme. @wilsonfreitas - would you be willing to add a license file?

**Comment by justinmayer** [comment]
I understand your motivation, but I don't think there's any need to create new issues for every theme that's missing a LICENSE file when there is already an open issue about this topic. If you want to get the author's attention, I think a comment in that issue would be sufficient. ☺️

**Comment by adrn** [comment]
Sounds good! I made a separate issue because the few other themes I clicked on all individually had licenses, but now I see there are others without licenses too.
