### ISSUE TITLE
pelican-bootstrap3: DISQUS doesn't work properly

### ISSUE THREAD

**Issue by ganziqim** [getpelican/pelican-themes#581]
I try the method put forward in #418 and #420 and it is feasible.

Is there someone going to fix it and merge into branch master?

**Comment by justinmayer** [comment]
If someone would like to submit a discrete pull request that re-enables Disqus for this theme, we'd be happy to merge it.

@ganziqim: Is this something you would like to help out with?

**Comment by ganziqim** [comment]
@justinmayer Yes, I will try to find a good way to fix it.

**Comment by justinmayer** [comment]
Addressed via aforementioned PR.
