### ISSUE TITLE
Gum theme: Multi font title

### ISSUE THREAD

**Issue by ghost** [getpelican/pelican-themes#605]
In the screenshot for the gum theme, the first line is normal font and the second line is bolded. I've tried looking around for a title setting to accomplish this but I haven't been able to find anything. Could someone point me in the right direction?

**Comment by rask004** [comment]
In your pelican config, add this variable:

SITESUBTITLE = 'subtitle'

I will update the gum documentation to point this out.

**Comment by justinmayer** [comment]
Thanks for providing a documentation fix for this issue, Roland! 👍
