### ISSUE TITLE
Change URL pointing to Elegant repository

### ISSUE THREAD

**Issue by silverhook** [getpelican/pelican-themes#623]
Recently Elegant grew into a community-based effort and to reflect that, changed its (GitHub) organisation as well as governance (see https://github.com/Pelican-Elegant/elegant/issues/173 for more info).

As part of that the main repository has changed from:
https://github.com/talha131/pelican-elegant/
to:
https://github.com/Pelican-Elegant/elegant

The redirect seems to be working, but for the future it would be good to point to the right repository. 

(teaser: we’re working on releasing 2.0 soon, and plans for 3.0 are already under discussion)

**Comment by iranzo** [comment]
@justinmayer can you have a look on this?  Thanks!

**Comment by justinmayer** [comment]
Would be easier to do so if there were clearer instructions as to the exact perceived steps required to close this issue.

**Comment by silverhook** [comment]
I haven’t done this before, but I would guess that in the `.gitmodules` file Elegant’s block should now say:

``` ini
[submodule "elegant"]
    path = elegant
    url = https://github.com/Pelican-Elegant/elegant.git
```

@talha131, can you provide more info on how this is to be done? You have done this before.

**Comment by iranzo** [comment]
I'll submit PR for it
Pablo Iranzo Gómez

GnuPG: 0x5BD8E1E4
Web: https://iranzo.github.io  ||  https://citellus.org

**Comment by iranzo** [comment]
Done in https://github.com/getpelican/pelican-themes/pull/627

**Comment by talha131** [comment]
@silverhook You were right. @iranzo PR has fixed the issue. It just needs to be merged.
