### ISSUE TITLE
Pelicanthemes.com is down

### ISSUE THREAD

**Issue by hpincket** [getpelican/pelican-themes#674]
[pelicanthemes.com](http://pelicanthemes.com) is down with an "Internal Server Error"

To Reproduce:
* Visit [pelicanthemes.com](http://pelicanthemes.com)

I checked for duplicates before creating this ticket.

**Comment by avaris** [comment]
Works for me.

**Comment by justinmayer** [comment]
pelicanthemes.com also loads fine for me.
