### ISSUE TITLE
pelican-b-side is a broken link

### ISSUE THREAD

**Issue by GiovanH** [getpelican/pelican-themes#683]
The repository linked by `pelican-b-side` is a broken link.

Should probably replace it with an archived version or remove the link from the repository.

**Comment by justinmayer** [comment]
@jhauh: Since the `pelican-b-side` repository no longer exists, nor the https://github.com/fluffactually organization under which it was submitted, is there another place we could find the `pelican-b-side` theme?

**Comment by jhauh** [comment]
Hey! This is my bad, and a result of two things:

* I changed my username from fluffactually to jhauh (I am fluffactually!)
* I migrated most of my personal repos from GitHub over to GitLab

In my defense, I did close the Pull Request once the links were broken, and before it was merged.

I will submit a new PR which updates the links to the new locations shortly, and I'll reference this issue. Thanks!

**Comment by justinmayer** [comment]
@jhauh: No worries at all. Thanks for the new PR that fixes it. 😁
