### ISSUE TITLE
Pull pelican-themes failing due to blueidea theme

### ISSUE THREAD

**Issue by tprrt** [getpelican/pelican-themes#694]
Hello,

The git repository of the blueidea theme seems no longer available (or public) then it is no longer possible to clone pelican-themes:
`git clone --recursive https://github.com/getpelican/pelican-themes`

Cloning into '/home/circleci/project/pelican-themes/blueidea'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://github.com/blueicefield/pelican-blueidea.git' into submodule path '/home/circleci/project/pelican-themes/blueidea' failed

**Comment by virtadpt** [comment]
Same here, earlier this evening.

**Comment by justinmayer** [comment]
Reason number 837 why I loathe Git submodules and why we are working to rid them from Pelican altogether.

Okay, fixed. Can you confirm that you are able to recursively clone the repository now?

**Comment by tprrt** [comment]
Dear @justinmayer,

I don't confirm because that I am able to recursively clone the repository now over ssh. Now a Github login and password are requested.

Best regards,
Thomas

**Comment by justinmayer** [comment]
I suggest trying via HTTPS as the README states. I was able to use that method without problems.

**Comment by tprrt** [comment]
Dear @justinmayer,

Okay, I confirm that it is fixed, thanks you.

Best regards,
Thomas

**Comment by virtadpt** [comment]
Same reason I dislike Git submodules.
...
Yup, looks like it worked.
