### ISSUE TITLE
themes/minimalX is not working anymore

### ISSUE THREAD

**Issue by maf88** [getpelican/pelican-themes#706]
When cloning, my username and pw are asked
```
Cloning into '/.../themes/minimalX'...
Username for 'https://github.com': 
Password for 'https://github.com': 
```

Then if you try to follow the link provided in the repo, ([here](https://github.com/art1fa/minimalX/tree/4b93146a2a38f4f156442f1795491582a4d8146a)) it is a 404 error.

**Comment by johnmarkschofield** [comment]
Confirmed here.

Would it be acceptable to submit a PR that just nuked this theme? It's kind of disruptive to not be able to DL the entire repo because of this.

**Comment by avaris** [comment]
Given that the original repo seems to be vanished, I am OK with removing the submodule from here.

**Comment by justinmayer** [comment]
I removed the minimalX theme via a3354d2. Would someone please confirm that has resolved this issue?

**Comment by johnmarkschofield** [comment]
This resolved the issue, but the minimalX directory is still present, just empty. Would it be more correct to remove the directory as well?

Thanks very much for fixing this!

**Comment by justinmayer** [comment]
Okay, I think I actually removed it this time. 😅  Let me know if that's not the case.
