### ISSUE TITLE
"bricks" theme: can't add social links

### ISSUE THREAD

**Issue by HengryYang** [getpelican/pelican-themes#712]
I tried to modify the social ink in pelicanconf.py:

SOCIAL = (('anything', 'social_link_here'),)

But there's no social link area on "bricks" theme home page, or any other page.

Am I doing this wrong, or is there just no this feature? Thx!

**Comment by rilysh** [comment]
Late reply but you need to add your social links in the `LINKS` variable instead `SOCIAL`.
Create a tuple and add your links there.

e.g.
```py
LINKS = (('example', 'https://example.com')
         ('...',  'https://example.net'))
```

**Comment by justinmayer** [comment]
Thanks for the helpful suggestion, @rilysh! 😊

**Comment by HengryYang** [comment]
Thanks too @rilysh! 😊
