### ISSUE TITLE
http://www.pelicanthemes.com/ not working

### ISSUE THREAD

**Issue by EnginKarahan** [getpelican/pelican-themes#713]
http://www.pelicanthemes.com/ is not working. Calling the page is returning an Internal Server Error

**Comment by maphew** [comment]
in a fun bit of meaningless coincidence, #731 is a dupe, but it also probably has the answer to the current brokenness: end of Heroku free tier.

**Comment by maphew** [comment]
I've built a replacement preview method, see #740

**Comment by EnginKarahan** [comment]
Great, your replacement ist working fine.
