### ISSUE TITLE
Lab theme is broken

### ISSUE THREAD

**Issue by RogueScholar** [getpelican/pelican-themes#714]
Just tried to clone the repo on a new computer and it errored out when trying to clone the [`lab`](https://github.com/getpelican/pelican-themes/lab) submodule; it seems [the creator/owner](https://github.com/mothsART) decided to summarily delete the entire repo the submodule points to without telling anyone. I never used it so I don't know how much of a loss it is, but in case it had some devotees ~~I searched the Wayback Machine for it and discovered that the repo had indeed been [archived](https://web.archive.org/web/20201005231327/https://github.com/mothsART/pelican-lab) just a little over a year ago.~~ Scratch that, I just checked the contents and they're not there, just the landing page and README.rst file. Well, I have no idea how long it's been since I last pulled the copy of the repo that's on my laptop from here (could be a couple years old or more, if memory serves), but you guys are welcome to it if you want to salvage the theme, just let me know and I'll make a tarball and attach it here.

Warmly,
Peter

**Comment by sophiasage** [comment]
I can't clone pelican-themes because of this problem. 
I get the error 
fatal: clone of 'https://github.com/mothsART/pelican-lab.git' into submodule path '/Users/myname/pelican-themes/lab' failed

**Comment by justinmayer** [comment]
Thanks to @avaris, this problem should now be resolved.
