### ISSUE TITLE
Pure theme repo is not exists anymore.

### ISSUE THREAD

**Issue by kamyanskiy** [getpelican/pelican-themes#723]
Seems Pure theme repo is not present anymore, on attempt to clone pelican-themes I see error:
```
fatal: Authentication failed for 'https://github.com/danclaudiupop/pure.git/'
fatal: clone of 'https://github.com/danclaudiupop/pure.git' into submodule path '/home/matrix/pelican-themes/pure' failed
Failed to clone 'pure' a second time, aborting

```

https://github.com/danclaudiupop/pure/tree/9c58a20c1ed86a26c456ac1f3a736838b6409fc1

![image](https://user-images.githubusercontent.com/1260333/153478273-a7bb5ed9-e37c-46fd-a518-1d6ce7e6f930.png)

**Comment by bcopy** [comment]
This is failing recursive cloning of the repo, please remove the Pure theme.
