### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by KrlitosForever** [getpelican/pelican-themes#742]
Hello everyone, when entering the web page it throws the following error.

![image](https://user-images.githubusercontent.com/7423579/211801074-86abb135-6497-4852-8620-29a93b957b28.png)

Regards!

**Comment by maphew** [comment]
Yeah, it's because Heroku discontinued the free tier service. See #731

**Comment by justinmayer** [comment]
Closing in favor of previously-mentioned linked issue.
