### ISSUE TITLE
The submodule links to alchemy, bulrush, neat are incorrect

### ISSUE THREAD

**Issue by tsengjun** [getpelican/pelican-themes#763]
Hello Guys,
The following three themes were linked to improper git submodule location.

- alchemy  
- bulrush  
- neat  

The authors put their source code in a sub directory, not the repository's root.
And they all have no activities for years, seems not an option to update these themes.

Can you help out and update submodule links here?

Thanks!

**Comment by tsengjun** [comment]
Take it as a note. Not a big problem.

**Comment by avaris** [comment]
This cannot be fixed here. Submodules cannot link to a subfolder, they are for entire repo. It needs to be done in the original repo.
