### ISSUE TITLE
Bootstrap theme class icons.

### ISSUE THREAD

**Issue by guillermomarco** [getpelican/pelican-themes#90]
I'm trying to include <i class="icon-search"></i> inside metadata.html in Bootstrap theme.
But this isn't working.

Any idea how to fix it? It should work since metadata.html is included in index.html and that file has bootstrap css.

**Comment by mandaris** [comment]
Can we close this issue?

**Comment by justinmayer** [comment]
@mandaris: Indeed we can. Thank you for the reminder!
